#include "1. Recursion/01-head_recursion.c"
#include "1. Recursion/02-tail_recursion.c"
#include "1. Recursion/03-static_variables_in_recursion.c"
#include "1. Recursion/04-global_variables_in_recursion.c"
#include "1. Recursion/05-tree_recursion.c"
#include "1. Recursion/06-indirect_recursion.c"
#include "1. Recursion/07-nested_recursion.c"
#include "1. Recursion/08-sum_of_n_natural_numbers.c"
#include "1. Recursion/09-factorial_of_n.c"
#include "1. Recursion/10-power_function.c"
#include "1. Recursion/11-taylor_series_using_static_variables.c"
#include "1. Recursion/12-taylor_series_horners_rule.c"
#include "1. Recursion/13-taylor_series_iterative.c"
#include "1. Recursion/14-fibonacci.c"
#include "1. Recursion/15-combination_formula.c"
#include "1. Recursion/16-tower_of_hanoi.c"
#include "10. Queue/01-queueArray.c"
#include "10. Queue/02-QueueUsingArrayC++.cpp"
#include "10. Queue/03-CircularQueueUsingArrayC++.cpp"
#include "10. Queue/04-queueLinkedList.c"
#include "10. Queue/05-QueueUsingLLC++.cpp"
#include "10. Queue/06-DequeueUsingArrayC++.cpp"
#include "10. Queue/07-QueueUsing2STLStacksC++.cpp"
#include "11. Trees/01-trees.c"
#include "11. Trees/02-CreateTreeUsingArrayQueueC++.cpp"
#include "11. Trees/03-TreeIterativeOrderTraversalUsingSTLStackC++.cpp"
#include "11. Trees/04-LevelOrderTraversalC++.cpp"
#include "11. Trees/05-GeneratingTreeFromTraversalC++.cpp"
#include "11. Trees/06-Height_CountofBinaryTreeC++.cpp"
#include "11. Trees/07-CountLeafofBinaryTreeC++.cpp"
#include "12. Binary Search Trees/01-binarySearchTrees.c"
#include "12. Binary Search Trees/02-BSTInsertInorder_SearchC++.cpp"
#include "12. Binary Search Trees/03-RecursiveInsert_DeleteonBSTC++.cpp"
#include "12. Binary Search Trees/04-BSTfromPreorderUsingSTLStackC++.cpp"
#include "13. Heap/01-heap.c"
#include "13. Heap/02-InsertinHeapC++.cpp"
#include "13. Heap/03-CreateHeapUsingSTLVectorC++.cpp"
#include "13. Heap/04-HeapifyFunctionFasterMethodtoCreateHeapC++.cpp"
#include "14. Sorting Techniques/01-sort.c"
#include "14. Sorting Techniques/02-BubbleSortC++.cpp"
#include "14. Sorting Techniques/03-InsertionSortC++.cpp"
#include "14. Sorting Techniques/04-SelectionSortC++.cpp"
#include "14. Sorting Techniques/05-QuickSortUsingINT_MAXOrInfinityC++.cpp"
#include "14. Sorting Techniques/06-MergingFunctionC++.cpp"
#include "14. Sorting Techniques/07-IterativeMergeSortC++.cpp"
#include "14. Sorting Techniques/08-RecursiveMergeSortC++.cpp"
#include "14. Sorting Techniques/09-CountSortFunctionC++.cpp"
#include "14. Sorting Techniques/10-RadixSortUsingLLC++.cpp"
#include "14. Sorting Techniques/11-ShellSortC++.cpp"
#include "15. Hashing Techniques/01-chainHashing.c"
#include "15. Hashing Techniques/02-HashTableClassChainingC++.cpp"
#include "15. Hashing Techniques/03-linearProbing.c"
#include "15. Hashing Techniques/04-HashTableLinearProbingC++.cpp"
#include "15. Hashing Techniques/05-quadraticProbing.c"
#include "15. Hashing Techniques/06-HashTableQuadraticProbingC++.cpp"
#include "15. Hashing Techniques/07-DoubleHashingC++.cpp"
#include "2. Array Representation/01-array_declaration.c"
#include "2. Array Representation/02-static_vs_dynamic_arrays.c"
#include "2. Array Representation/03-array_size.c"
#include "2. Array Representation/04-2D_arrray.c"
#include "3. Array ADT/01-array_ADT.c"
#include "3. Array ADT/02-demo_array_ADT_C++.cpp"
#include "3. Array ADT/03-inserting_and_appending_in_a_array.c"
#include "3. Array ADT/04-deleting_from_array.c"
#include "3. Array ADT/05-searching_in_a_array.c"
#include "3. Array ADT/06-binary_search_in_array.c"
#include "3. Array ADT/07-get_set_max_min_on_array.c"
#include "3. Array ADT/08-reversing_an_array.c"
#include "3. Array ADT/09-checking_if_array_is_sorted.c"
#include "3. Array ADT/10-merge_2_arrays.c"
#include "3. Array ADT/11-merge_arrays_C++.cpp"
#include "3. Array ADT/12-set_operations_on_array.c"
#include "3. Array ADT/13-array_menu_using_c.c"
#include "3. Array ADT/14-array_C++.cpp"
#include "3. Array ADT/15-array_C++_modified.cpp"
#include "3. Array ADT/16-student_exercise.c"
#include "4. Strings/01-string.c"
#include "5. Matrices/01-diagonal_matrix_c.c"
#include "5. Matrices/02-diagonal_matrix_cpp.cpp"
#include "5. Matrices/03-lower_triangular_matrix_c.c"
#include "5. Matrices/04-lower_triangular_matrix_cpp.cpp"
#include "6. Sparse Matrix and Polynomial Representation/01-sparse_matrix_using_c.c"
#include "6. Sparse Matrix and Polynomial Representation/02-sparse_matrix_using_c++.cpp"
#include "6. Sparse Matrix and Polynomial Representation/03-polynomial_representation.c"
#include "7. Linked List/01-linkedList.c"
#include "7. Linked List/02-middleElement.cpp"
#include "7. Linked List/03-intersectingPoint.cpp"
#include "8. Sparse Matrix and Polynomial using Linked List/01-polynomial.c"
#include "9. Stack/01-stackArray.c"
#include "9. Stack/02-StackUsingArrayC++.cpp"
#include "9. Stack/03-stackLinkedList.c"
#include "9. Stack/04-StackUsingLLC++.cpp"
#include "9. Stack/05-ParanthesisMatchingC++.cpp"
#include "9. Stack/06-InfixToPostfixUsingSTLStackC++.cpp"
#include "9. Stack/07-PostfixEvaluationUsingLLStack_STLC++.cpp"